package view;

import controller.ControllerProdutos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelProdutos;

public class ViewProduto extends javax.swing.JFrame {

    ArrayList<ModelProdutos> listaModelProdutos = new ArrayList<>();
    ControllerProdutos controllerProdutos = new ControllerProdutos();
    ModelProdutos modelProdutos = new ModelProdutos();
    String salvarAlterar;
    
    /**
     * Creates new form ViewProdutos
     */
    public ViewProduto() {
        initComponents();
        carregarProdutos();
        setLocationRelativeTo(null);
        habilitarDesabilitarCampos(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbNovo = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JLabel();
        jpCadastroProdutos = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfPreco = new javax.swing.JFormattedTextField();
        jtfEstoque = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfObs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfDescricao = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JLabel();
        jtfPesquisar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        jbPesquisar = new javax.swing.JLabel();
        jbAlterar = new javax.swing.JLabel();
        jbExcluir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Produtos");

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/new.png"))); // NOI18N
        jbNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbNovoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbNovoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbNovoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbNovoMouseReleased(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/save.png"))); // NOI18N
        jbSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSalvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbSalvarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbSalvarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbSalvarMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNovo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbSalvar)
                    .addComponent(jbNovo)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpCadastroProdutos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Formulário de cadastro");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Código");

        jtfId.setEditable(false);
        jtfId.setEnabled(false);
        jtfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Preço");

        jtfPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jtfPreco.setDisabledTextColor(new java.awt.Color(102, 153, 255));

        jtfEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtfEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEstoqueActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Estoque");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Observações");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Descrição");

        jtfDescricao.setColumns(20);
        jtfDescricao.setRows(3);
        jScrollPane1.setViewportView(jtfDescricao);

        javax.swing.GroupLayout jpCadastroProdutosLayout = new javax.swing.GroupLayout(jpCadastroProdutos);
        jpCadastroProdutos.setLayout(jpCadastroProdutosLayout);
        jpCadastroProdutosLayout.setHorizontalGroup(
            jpCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastroProdutosLayout.createSequentialGroup()
                        .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNome))
                    .addGroup(jpCadastroProdutosLayout.createSequentialGroup()
                        .addGroup(jpCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCadastroProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfObs)))
                    .addGroup(jpCadastroProdutosLayout.createSequentialGroup()
                        .addGroup(jpCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jpCadastroProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpCadastroProdutosLayout.setVerticalGroup(
            jpCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfObs, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Lista de produtos");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Pesquisar");

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/cancel.png"))); // NOI18N
        jbCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCancelarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbCancelarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbCancelarMouseReleased(evt);
            }
        });

        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Preço", "Estoque"
            }
        ));
        jScrollPane2.setViewportView(jtProdutos);
        if (jtProdutos.getColumnModel().getColumnCount() > 0) {
            jtProdutos.getColumnModel().getColumn(0).setPreferredWidth(40);
            jtProdutos.getColumnModel().getColumn(2).setPreferredWidth(60);
            jtProdutos.getColumnModel().getColumn(3).setPreferredWidth(60);
        }

        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/search.png"))); // NOI18N
        jbPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbPesquisarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbPesquisarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbPesquisarMouseReleased(evt);
            }
        });

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/edit.png"))); // NOI18N
        jbAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAlterarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbAlterarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbAlterarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbAlterarMouseReleased(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/delete.png"))); // NOI18N
        jbExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbExcluirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbExcluirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbExcluirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbExcluirMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfPesquisar)
                        .addGap(10, 10, 10)
                        .addComponent(jbPesquisar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancelar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbPesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jbCancelar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbAlterar)
                            .addComponent(jbExcluir))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpCadastroProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCadastroProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSalvarMouseReleased
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/save.png")));
    }//GEN-LAST:event_jbSalvarMouseReleased

    private void jbSalvarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSalvarMousePressed
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/saveclicked.png")));
    }//GEN-LAST:event_jbSalvarMousePressed

    private void jbSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSalvarMouseExited
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/save.png")));
    }//GEN-LAST:event_jbSalvarMouseExited

    private void jbSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSalvarMouseEntered
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/savehover.png")));
    }//GEN-LAST:event_jbSalvarMouseEntered

    private void jbSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSalvarMouseClicked
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/saveclicked.png")));
        if(salvarAlterar.equals("salvar")) {
            this.salvarProduto();
        } else if (salvarAlterar.equals("alterar")) {
            this.alterarProduto();
        }
    }//GEN-LAST:event_jbSalvarMouseClicked

    private void jbNovoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNovoMouseReleased
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/new.png")));
    }//GEN-LAST:event_jbNovoMouseReleased

    private void jbNovoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNovoMousePressed
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/newclicked.png")));
    }//GEN-LAST:event_jbNovoMousePressed

    private void jbNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNovoMouseExited
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/new.png")));
    }//GEN-LAST:event_jbNovoMouseExited

    private void jbNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNovoMouseEntered
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/newhover.png")));
    }//GEN-LAST:event_jbNovoMouseEntered

    private void jbNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNovoMouseClicked
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/newclicked.png")));
        habilitarDesabilitarCampos(true);
        salvarAlterar = "salvar";
    }//GEN-LAST:event_jbNovoMouseClicked

    private void jtfEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEstoqueActionPerformed

    private void jtfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdActionPerformed

    private void jbCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelarMouseClicked
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/cancelclicked.png")));
        habilitarDesabilitarCampos(false);
        limparCampos();
    }//GEN-LAST:event_jbCancelarMouseClicked

    private void jbCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelarMouseEntered
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/cancelhover.png")));
    }//GEN-LAST:event_jbCancelarMouseEntered

    private void jbCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelarMouseExited
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/cancel.png")));
    }//GEN-LAST:event_jbCancelarMouseExited

    private void jbCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelarMousePressed
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/cancelclicked.png")));
    }//GEN-LAST:event_jbCancelarMousePressed

    private void jbCancelarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelarMouseReleased
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/cancel.png")));
    }//GEN-LAST:event_jbCancelarMouseReleased

    private void jbPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPesquisarMouseClicked
        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/searchclicked.png")));
        DefaultTableModel modelo = (DefaultTableModel) this.jtProdutos.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.jtProdutos.setRowSorter(classificador);
        String texto = jtfPesquisar.getText();
        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    }//GEN-LAST:event_jbPesquisarMouseClicked

    private void jbPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPesquisarMouseEntered
        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/searchhover.png")));
    }//GEN-LAST:event_jbPesquisarMouseEntered

    private void jbPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPesquisarMouseExited
        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/search.png")));
    }//GEN-LAST:event_jbPesquisarMouseExited

    private void jbPesquisarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPesquisarMousePressed
        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/searchclicked.png")));
    }//GEN-LAST:event_jbPesquisarMousePressed

    private void jbPesquisarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPesquisarMouseReleased
        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/search.png")));
    }//GEN-LAST:event_jbPesquisarMouseReleased

    private void jbAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAlterarMouseClicked
        salvarAlterar = "alterar";
        int linha = jtProdutos.getSelectedRow();
        
        try {
            int codigoProduto = (int) jtProdutos.getValueAt(linha, 0);
            habilitarDesabilitarCampos(true);
            //recupera dados do banco
            modelProdutos = controllerProdutos.getProdutoController(codigoProduto);
            //setar na interface
            this.jtfId.setText(String.valueOf(modelProdutos.getProdId()));
            this.jtfNome.setText(modelProdutos.getProdNome());
            this.jtfDescricao.setText(modelProdutos.getProdDescricao());
            this.jtfObs.setText(modelProdutos.getProdObs());
            this.jtfPreco.setText(String.valueOf(modelProdutos.getProdPreco()));
            this.jtfEstoque.setText(String.valueOf(modelProdutos.getProdEstoque()));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado");
        }
    }//GEN-LAST:event_jbAlterarMouseClicked

    private void jbAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAlterarMouseEntered
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/edithover.png")));
    }//GEN-LAST:event_jbAlterarMouseEntered

    private void jbAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAlterarMouseExited
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/edit.png")));
    }//GEN-LAST:event_jbAlterarMouseExited

    private void jbAlterarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAlterarMousePressed
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/editclicked.png")));
    }//GEN-LAST:event_jbAlterarMousePressed

    private void jbAlterarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAlterarMouseReleased
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/edit.png")));
    }//GEN-LAST:event_jbAlterarMouseReleased

    private void jbExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExcluirMouseClicked
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/deleteclicked.png")));
        int linha = jtProdutos.getSelectedRow();
        int codigoProduto = (int) jtProdutos.getValueAt(linha, 0);
        
        if(controllerProdutos.excluirProdutoController(codigoProduto)) {
            JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!", "Pronto!", JOptionPane.WARNING_MESSAGE);
            this.carregarProdutos();
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível excluir o produto!", "Erro", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_jbExcluirMouseClicked

    private void jbExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExcluirMouseEntered
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/deletehover.png")));
    }//GEN-LAST:event_jbExcluirMouseEntered

    private void jbExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExcluirMouseExited
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/delete.png")));
    }//GEN-LAST:event_jbExcluirMouseExited

    private void jbExcluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExcluirMousePressed
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/deleteclicked.png")));
    }//GEN-LAST:event_jbExcluirMousePressed

    private void jbExcluirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExcluirMouseReleased
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botões/delete.png")));
    }//GEN-LAST:event_jbExcluirMouseReleased

    /**
     * Limpa campos do formulário
     */
    private void limparCampos() {
        jtfId.setText("");
        jtfNome.setText("");
        jtfPreco.setText("");
        jtfEstoque.setText("");
        jtfObs.setText("");
        jtfDescricao.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProduto().setVisible(true);
            }
        });
    }

    
    private void salvarProduto() {
        // Botão salvar
        modelProdutos.setProdNome(this.jtfNome.getText());
        modelProdutos.setProdPreco(Double.parseDouble(this.jtfPreco.getText().replaceAll(",", ".")));
        modelProdutos.setProdEstoque(Integer.parseInt(this.jtfEstoque.getText()));
        modelProdutos.setProdObs(this.jtfObs.getText());
        modelProdutos.setProdDescricao(this.jtfDescricao.getText());
        
        if(controllerProdutos.salvarProdutoController(modelProdutos) > 0) {
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!", "Pronto!", JOptionPane.WARNING_MESSAGE);
            this.carregarProdutos();
            this.limparCampos();
            this.habilitarDesabilitarCampos(false);
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível cadastrar o produto!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void alterarProduto() {
        // Botão alterar
        modelProdutos.setProdNome(this.jtfNome.getText());
        modelProdutos.setProdPreco(Double.parseDouble(this.jtfPreco.getText().replaceAll(",", ".")));
        modelProdutos.setProdEstoque(Integer.parseInt(this.jtfEstoque.getText()));
        modelProdutos.setProdObs(this.jtfObs.getText());
        modelProdutos.setProdDescricao(this.jtfNome.getText());
        
        if(controllerProdutos.alterarProdutoController(modelProdutos)) {
            JOptionPane.showMessageDialog(this, "Produto alterado com sucesso!", "Pronto!", JOptionPane.WARNING_MESSAGE);
            this.carregarProdutos();
            this.limparCampos();
            this.habilitarDesabilitarCampos(false);
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível alterar o produto!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Habilita ou desabilta os campos do formulário
     * @param condicao 
     */
    private void habilitarDesabilitarCampos(boolean condicao) {
        jtfNome.setEnabled(condicao);
        jtfPreco.setEnabled(condicao);
        jtfDescricao.setEnabled(condicao);
        jtfObs.setEnabled(condicao);
        jtfEstoque.setEnabled(condicao);
    }
    
    /**
     * Preencher a tabela com os produtos cadastrados no banco
     */
    private void carregarProdutos() {
        listaModelProdutos = controllerProdutos.getListaProdutosController();
        DefaultTableModel modelo = (DefaultTableModel) jtProdutos.getModel();
        modelo.setNumRows(0);
        
        // Inserir na tabela
        int cont = listaModelProdutos.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[] {
                listaModelProdutos.get(i).getProdId(),
                listaModelProdutos.get(i).getProdNome(),
                "R$ " + listaModelProdutos.get(i).getProdPreco(),
                listaModelProdutos.get(i).getProdEstoque()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jbAlterar;
    private javax.swing.JLabel jbCancelar;
    private javax.swing.JLabel jbExcluir;
    private javax.swing.JLabel jbNovo;
    private javax.swing.JLabel jbPesquisar;
    private javax.swing.JLabel jbSalvar;
    private javax.swing.JPanel jpCadastroProdutos;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JTextArea jtfDescricao;
    private javax.swing.JFormattedTextField jtfEstoque;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfObs;
    private javax.swing.JTextField jtfPesquisar;
    private javax.swing.JFormattedTextField jtfPreco;
    // End of variables declaration//GEN-END:variables
}
